package com.ine.backend.entities;

/**
 * Domain enum representing different technology and engineering
 * majors/specializations
 */
public enum Domain {

	// Software & Development
	SOFTWARE_ENGINEERING, WEB_DEVELOPMENT, MOBILE_DEVELOPMENT, FULL_STACK_DEVELOPMENT,

	// Data & Analytics
	DATA_SCIENCE, DATA_ENGINEERING, MACHINE_LEARNING, ARTIFICIAL_INTELLIGENCE, BIG_DATA,

	// Infrastructure & Cloud
	CLOUD_COMPUTING, DEVOPS, INFRASTRUCTURE, SYSTEM_ADMINISTRATION,

	// Security
	CYBERSECURITY, NETWORK_SECURITY, INFORMATION_SECURITY,

	// Emerging Technologies
	INTERNET_OF_THINGS, BLOCKCHAIN, ROBOTICS, AUGMENTED_REALITY, VIRTUAL_REALITY,

	// Networks & Systems
	NETWORKING, DATABASE_ADMINISTRATION, SYSTEM_DESIGN,

	// UI/UX & Design
	UI_UX_DESIGN, PRODUCT_DESIGN,

	// Management & Business
	PRODUCT_MANAGEMENT, PROJECT_MANAGEMENT, TECH_LEADERSHIP,

	// Quality & Testing
	QUALITY_ASSURANCE, SOFTWARE_TESTING,

	// General & Others
	COMPUTER_SCIENCE, INFORMATION_TECHNOLOGY, RESEARCH_DEVELOPMENT, OTHER
}
